run:
  timeout: 10m

output:
  formats: colored-line-number

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - exportloopref
    - gofmt
    - goimports
    - gosimple
    - govet
    - grouper
    - ineffassign
    - makezero
    - misspell
    - nosprintfhostport
    - reassign
    - tparallel
    - typecheck
    - unconvert
    - unparam
