// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: dcrrates.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DCRRates_SubscribeExchanges_FullMethodName = "/dcrrates.DCRRates/SubscribeExchanges"
)

// DCRRatesClient is the client API for DCRRates service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DCRRates takes a subscription from a client and pushes data as its received
// from external sources.
type DCRRatesClient interface {
	SubscribeExchanges(ctx context.Context, in *ExchangeSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExchangeRateUpdate], error)
}

type dCRRatesClient struct {
	cc grpc.ClientConnInterface
}

func NewDCRRatesClient(cc grpc.ClientConnInterface) DCRRatesClient {
	return &dCRRatesClient{cc}
}

func (c *dCRRatesClient) SubscribeExchanges(ctx context.Context, in *ExchangeSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExchangeRateUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DCRRates_ServiceDesc.Streams[0], DCRRates_SubscribeExchanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExchangeSubscription, ExchangeRateUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DCRRates_SubscribeExchangesClient = grpc.ServerStreamingClient[ExchangeRateUpdate]

// DCRRatesServer is the server API for DCRRates service.
// All implementations must embed UnimplementedDCRRatesServer
// for forward compatibility.
//
// DCRRates takes a subscription from a client and pushes data as its received
// from external sources.
type DCRRatesServer interface {
	SubscribeExchanges(*ExchangeSubscription, grpc.ServerStreamingServer[ExchangeRateUpdate]) error
	mustEmbedUnimplementedDCRRatesServer()
}

// UnimplementedDCRRatesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDCRRatesServer struct{}

func (UnimplementedDCRRatesServer) SubscribeExchanges(*ExchangeSubscription, grpc.ServerStreamingServer[ExchangeRateUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeExchanges not implemented")
}
func (UnimplementedDCRRatesServer) mustEmbedUnimplementedDCRRatesServer() {}
func (UnimplementedDCRRatesServer) testEmbeddedByValue()                  {}

// UnsafeDCRRatesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DCRRatesServer will
// result in compilation errors.
type UnsafeDCRRatesServer interface {
	mustEmbedUnimplementedDCRRatesServer()
}

func RegisterDCRRatesServer(s grpc.ServiceRegistrar, srv DCRRatesServer) {
	// If the following call pancis, it indicates UnimplementedDCRRatesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DCRRates_ServiceDesc, srv)
}

func _DCRRates_SubscribeExchanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExchangeSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DCRRatesServer).SubscribeExchanges(m, &grpc.GenericServerStream[ExchangeSubscription, ExchangeRateUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DCRRates_SubscribeExchangesServer = grpc.ServerStreamingServer[ExchangeRateUpdate]

// DCRRates_ServiceDesc is the grpc.ServiceDesc for DCRRates service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DCRRates_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dcrrates.DCRRates",
	HandlerType: (*DCRRatesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeExchanges",
			Handler:       _DCRRates_SubscribeExchanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dcrrates.proto",
}
