// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dcrrates.proto

package dcrrates

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExchangeSubscription struct {
	BtcIndex             string   `protobuf:"bytes,1,opt,name=btcIndex,proto3" json:"btcIndex,omitempty"`
	Exchanges            []string `protobuf:"bytes,2,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeSubscription) Reset()         { *m = ExchangeSubscription{} }
func (m *ExchangeSubscription) String() string { return proto.CompactTextString(m) }
func (*ExchangeSubscription) ProtoMessage()    {}
func (*ExchangeSubscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcrrates_dcd22285f4ba2133, []int{0}
}
func (m *ExchangeSubscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeSubscription.Unmarshal(m, b)
}
func (m *ExchangeSubscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeSubscription.Marshal(b, m, deterministic)
}
func (dst *ExchangeSubscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeSubscription.Merge(dst, src)
}
func (m *ExchangeSubscription) XXX_Size() int {
	return xxx_messageInfo_ExchangeSubscription.Size(m)
}
func (m *ExchangeSubscription) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeSubscription.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeSubscription proto.InternalMessageInfo

func (m *ExchangeSubscription) GetBtcIndex() string {
	if m != nil {
		return m.BtcIndex
	}
	return ""
}

func (m *ExchangeSubscription) GetExchanges() []string {
	if m != nil {
		return m.Exchanges
	}
	return nil
}

type ExchangeRateUpdate struct {
	Token                string             `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Price                float64            `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	BaseVolume           float64            `protobuf:"fixed64,3,opt,name=baseVolume,proto3" json:"baseVolume,omitempty"`
	Volume               float64            `protobuf:"fixed64,4,opt,name=volume,proto3" json:"volume,omitempty"`
	Change               float64            `protobuf:"fixed64,5,opt,name=change,proto3" json:"change,omitempty"`
	Stamp                int64              `protobuf:"varint,6,opt,name=stamp,proto3" json:"stamp,omitempty"`
	Indices              map[string]float64 `protobuf:"bytes,7,rep,name=indices,proto3" json:"indices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ExchangeRateUpdate) Reset()         { *m = ExchangeRateUpdate{} }
func (m *ExchangeRateUpdate) String() string { return proto.CompactTextString(m) }
func (*ExchangeRateUpdate) ProtoMessage()    {}
func (*ExchangeRateUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcrrates_dcd22285f4ba2133, []int{1}
}
func (m *ExchangeRateUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRateUpdate.Unmarshal(m, b)
}
func (m *ExchangeRateUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRateUpdate.Marshal(b, m, deterministic)
}
func (dst *ExchangeRateUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRateUpdate.Merge(dst, src)
}
func (m *ExchangeRateUpdate) XXX_Size() int {
	return xxx_messageInfo_ExchangeRateUpdate.Size(m)
}
func (m *ExchangeRateUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRateUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRateUpdate proto.InternalMessageInfo

func (m *ExchangeRateUpdate) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ExchangeRateUpdate) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ExchangeRateUpdate) GetBaseVolume() float64 {
	if m != nil {
		return m.BaseVolume
	}
	return 0
}

func (m *ExchangeRateUpdate) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *ExchangeRateUpdate) GetChange() float64 {
	if m != nil {
		return m.Change
	}
	return 0
}

func (m *ExchangeRateUpdate) GetStamp() int64 {
	if m != nil {
		return m.Stamp
	}
	return 0
}

func (m *ExchangeRateUpdate) GetIndices() map[string]float64 {
	if m != nil {
		return m.Indices
	}
	return nil
}

func init() {
	proto.RegisterType((*ExchangeSubscription)(nil), "dcrrates.ExchangeSubscription")
	proto.RegisterType((*ExchangeRateUpdate)(nil), "dcrrates.ExchangeRateUpdate")
	proto.RegisterMapType((map[string]float64)(nil), "dcrrates.ExchangeRateUpdate.IndicesEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DCRRatesClient is the client API for DCRRates service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DCRRatesClient interface {
	SubscribeExchanges(ctx context.Context, in *ExchangeSubscription, opts ...grpc.CallOption) (DCRRates_SubscribeExchangesClient, error)
}

type dCRRatesClient struct {
	cc *grpc.ClientConn
}

func NewDCRRatesClient(cc *grpc.ClientConn) DCRRatesClient {
	return &dCRRatesClient{cc}
}

func (c *dCRRatesClient) SubscribeExchanges(ctx context.Context, in *ExchangeSubscription, opts ...grpc.CallOption) (DCRRates_SubscribeExchangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DCRRates_serviceDesc.Streams[0], "/dcrrates.DCRRates/SubscribeExchanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &dCRRatesSubscribeExchangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DCRRates_SubscribeExchangesClient interface {
	Recv() (*ExchangeRateUpdate, error)
	grpc.ClientStream
}

type dCRRatesSubscribeExchangesClient struct {
	grpc.ClientStream
}

func (x *dCRRatesSubscribeExchangesClient) Recv() (*ExchangeRateUpdate, error) {
	m := new(ExchangeRateUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DCRRatesServer is the server API for DCRRates service.
type DCRRatesServer interface {
	SubscribeExchanges(*ExchangeSubscription, DCRRates_SubscribeExchangesServer) error
}

func RegisterDCRRatesServer(s *grpc.Server, srv DCRRatesServer) {
	s.RegisterService(&_DCRRates_serviceDesc, srv)
}

func _DCRRates_SubscribeExchanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExchangeSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DCRRatesServer).SubscribeExchanges(m, &dCRRatesSubscribeExchangesServer{stream})
}

type DCRRates_SubscribeExchangesServer interface {
	Send(*ExchangeRateUpdate) error
	grpc.ServerStream
}

type dCRRatesSubscribeExchangesServer struct {
	grpc.ServerStream
}

func (x *dCRRatesSubscribeExchangesServer) Send(m *ExchangeRateUpdate) error {
	return x.ServerStream.SendMsg(m)
}

var _DCRRates_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dcrrates.DCRRates",
	HandlerType: (*DCRRatesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeExchanges",
			Handler:       _DCRRates_SubscribeExchanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dcrrates.proto",
}

func init() { proto.RegisterFile("dcrrates.proto", fileDescriptor_dcrrates_dcd22285f4ba2133) }

var fileDescriptor_dcrrates_dcd22285f4ba2133 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4b, 0x6b, 0xfa, 0x40,
	0x14, 0xc5, 0x99, 0xe4, 0xef, 0xeb, 0xfe, 0x4b, 0x29, 0x17, 0x29, 0x83, 0x88, 0x04, 0x57, 0xe9,
	0x46, 0x8a, 0xdd, 0x14, 0xb7, 0xd6, 0x85, 0xbb, 0x32, 0x7d, 0xac, 0x3b, 0x49, 0x2e, 0x6d, 0x50,
	0x27, 0x61, 0x66, 0x14, 0xfd, 0x44, 0xfd, 0x9a, 0x65, 0x32, 0x89, 0x0d, 0x08, 0xdd, 0xe5, 0x77,
	0x4e, 0xe6, 0x9e, 0xfb, 0x80, 0xeb, 0x2c, 0xd5, 0x5a, 0x5a, 0x32, 0xb3, 0x52, 0x17, 0xb6, 0xc0,
	0x7e, 0xc3, 0xd3, 0x67, 0x18, 0xae, 0x8e, 0xe9, 0x97, 0x54, 0x9f, 0xf4, 0xb2, 0x4f, 0x4c, 0xaa,
	0xf3, 0xd2, 0xe6, 0x85, 0xc2, 0x11, 0xf4, 0x13, 0x9b, 0xae, 0x55, 0x46, 0x47, 0xce, 0x22, 0x16,
	0x0f, 0xc4, 0x99, 0x71, 0x0c, 0x03, 0xaa, 0xdf, 0x18, 0x1e, 0x44, 0x61, 0x3c, 0x10, 0xbf, 0xc2,
	0xf4, 0x3b, 0x00, 0x6c, 0x4a, 0x0a, 0x69, 0xe9, 0xad, 0xcc, 0xa4, 0x25, 0x1c, 0x42, 0xc7, 0x16,
	0x1b, 0x52, 0x75, 0x35, 0x0f, 0x4e, 0x2d, 0x75, 0x9e, 0x12, 0x0f, 0x22, 0x16, 0x33, 0xe1, 0x01,
	0x27, 0x00, 0x89, 0x34, 0xf4, 0x5e, 0x6c, 0xf7, 0x3b, 0xe2, 0x61, 0x65, 0xb5, 0x14, 0xbc, 0x85,
	0xee, 0xc1, 0x7b, 0xff, 0x2a, 0xaf, 0x26, 0xa7, 0xfb, 0x5c, 0xde, 0xf1, 0xba, 0x27, 0x97, 0x62,
	0xac, 0xdc, 0x95, 0xbc, 0x1b, 0xb1, 0x38, 0x14, 0x1e, 0x70, 0x09, 0xbd, 0x5c, 0x65, 0x79, 0x4a,
	0x86, 0xf7, 0xa2, 0x30, 0xfe, 0x3f, 0xbf, 0x9b, 0x9d, 0xd7, 0x74, 0x39, 0xc0, 0x6c, 0xed, 0xff,
	0x5d, 0x29, 0xab, 0x4f, 0xa2, 0x79, 0x39, 0x5a, 0xc0, 0x55, 0xdb, 0xc0, 0x1b, 0x08, 0x37, 0x74,
	0xaa, 0x87, 0x74, 0x9f, 0x2e, 0xfc, 0x20, 0xb7, 0xfb, 0xf3, 0x88, 0x15, 0x2c, 0x82, 0x47, 0x36,
	0xff, 0x80, 0xfe, 0xd3, 0x52, 0xb8, 0x08, 0x83, 0xaf, 0x80, 0xf5, 0xfe, 0x13, 0x6a, 0xc2, 0x0d,
	0x4e, 0x2e, 0x3b, 0x6a, 0x5f, 0x69, 0x34, 0xfe, 0xab, 0xe3, 0x7b, 0x96, 0x74, 0xab, 0x73, 0x3f,
	0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xcb, 0x89, 0xa8, 0x00, 0x02, 0x00, 0x00,
}
